### ISSUE TITLE
Make an option to hide scrollbar after predefined timeout

### ISSUE THREAD

**Issue by e-pirate** [obcat/vim-sclow#9]
It will be nice to hide the scrollbar after some predefined period of time, so after moving up/down (but not within current screen) the scrollbar will disappear. In other words, if current "view" of the file/buffer changed, the scrollbar is displayed for some time to show you where is your position relative to the file content, but then disappears until position changes.
May be off by default:
`let g:sclow_hide = 0`
And enabled by changing value:
`let g:sclow_hide = 1000` - hide scrollbar after 1 second without changing position.
Moving/editing text without changing position relative to file should not trigger scrollbar emerging.

**Comment by obcat** [comment]
That sounds good.
Maybe timer can be used.

I'd like to try, but a bit busy recently.
I would be appreciated if you could make a PR.

**Comment by e-pirate** [comment]
Unfortunately, vim script is what I don't understand. I did a quick view on code and it looks like it is beyond my capabilities. It is just another universe to what I got used to.

**Comment by obcat** [comment]
I see. Thank you for checking.
I'll try when I have time.

**Comment by e-pirate** [comment]
To make my request even more clear, a can add that having a column on the right side of a modern size screen is not a problem. Even on my ageing "brick" every-day-carry 12" Lenovo X230 with it's emulated 169x42 is acceptable. 14"+ displays are not a concern at all. But being an SRE at a company shat has 10K+ servers in several data centres I have to service them all the time. A "dead" ones are our every day pain. In most cases non-booters are disk/network/other_hardware problems and can be brought back to life only with a help of SOL (serial over ethernet) console. But there some with pesky IPMIs that will not let you in with SOL and the only way to take control over such server is JAVA IPMI client that actually shows that is displayed on the physical display output. This is often the only way to reach the server with severe hardware problems (well, engineer with a pair of hands running in data centre halls left for the most last case) . The only downside of this that when you finally resuscitate the little bastard, you have to deal with slow updating 80x25 legacy console. And at this point any extra displayed element start to matter, at least until you get it on network again.

A mast admin the plugin is a masterpiece and does exactly that it expected to the way it should. It is more then usable in a current state and after several attempts in past couple of years this is the only one I put to my .vim and let it stay. The only feature left to wish for is an option to hide scrollbar after timeout. That said, I will patiently wait for it. Hope you will not abandon this plugin.

**Comment by e-pirate** [comment]
Hi!
Any progress/plans here?

**Comment by e-pirate** [comment]
@obcat finally, I implemented autohide myself using timer, please see: [pullrequst]( https://github.com/obcat/vim-sclow/pull/10 ).
